fix: add missing time import to collector.py
BUGFIX: NameError when collector.py tried to call time.time()
Missing 'import time' statement at top of file.

Error was:
  NameError: name 'time' is not defined